---
apiVersion: v1
kind: Service
metadata:
  name: wazuh-manager-lb
  annotations:
    external-dns.alpha.kubernetes.io/hostname: wazuh.${SECRET_DOMAIN}
    lbipam.cilium.io/ips: ${WAZUH_VIP_GATEWAY}
spec:
  type: LoadBalancer
  ports:
    - name: registration
      port: 1515
      targetPort: 1515
      protocol: TCP
    - name: agents
      port: 1514
      targetPort: 1514
      protocol: TCP
  selector:
    app: wazuh-manager
