---
apiVersion: v1
kind: Service
metadata:
  name: wazuh-manager
  labels:
    app: wazuh-manager
spec:
  type: ClusterIP
  ports:
    - name: registration
      port: 1515
      targetPort: 1515
    - name: agents
      port: 1514
      targetPort: 1514
    - name: api
      port: 55000
      targetPort: 55000
    - name: cluster
      port: 1516
      targetPort: 1516
  selector:
    app: wazuh-manager
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-manager
spec:
  serviceName: wazuh-manager
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-manager
  template:
    metadata:
      labels:
        app: wazuh-manager
    spec:
      containers:
        - name: wazuh-manager
          image: wazuh/wazuh-manager:4.9.2
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1Gi
          ports:
            - containerPort: 1515
              name: registration
            - containerPort: 1514
              name: agents
            - containerPort: 55000
              name: api
            - containerPort: 1516
              name: cluster
          env:
            - name: INDEXER_URL
              value: "http://wazuh-indexer:9200"
            - name: FILEBEAT_SSL_VERIFICATION_MODE
              value: "none"
            - name: API_USERNAME
              valueFrom:
                secretKeyRef:
                  name: wazuh-secret
                  key: API_USERNAME
            - name: API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wazuh-secret
                  key: API_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/ossec/data
            - name: config
              mountPath: /var/ossec/etc/ossec.conf
              subPath: ossec.conf
      volumes:
        - name: config
          configMap:
            name: wazuh-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: ceph-rbd
        resources:
          requests:
            storage: 10Gi
