---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vllm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: vllm-secret
    template:
      engineVersion: v2
      data:
        HF_TOKEN: "{{ .HF_TOKEN }}"
  dataFrom:
    - find:
        name:
          regexp: ^HF_TOKEN$
