---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app roundtable-shared-vault
  namespace: flux-system
spec:
  targetNamespace: roundtable
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/roundtable/shared-vault/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: dapper-cluster
  wait: true
  interval: 30m
  timeout: 5m
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
