libraries: # This is called out once within the config.yaml file
  4k-Movies:
    library_name: 4k-Movies
    run_order:
      - collections
      - metadata
      - operations
      - overlays
    collection_files:
      - repo: Movies.yaml
      - repo: People.yaml
      - pmm: basic
      - pmm: imdb
    overlay_files:
      - remove_overlays: false
      - repo: Movies - Overlays - Charts.yaml
      - repo: Movies - Overlays - Oscars.yaml
      - repo: Movies - Overlays - Ratings.yaml
      - repo: Movies - Overlays - Stand-up.yaml
      - repo: Movies - Overlays - Streaming Services.yaml
      - repo: Movies - Overlays - Studios.yaml
    operations:
      mass_genre_update: imdb
      mass_content_rating_update: [omdb, 2.0]
      mass_audience_rating_update: [mdb_tomatoesaudience, 2.0]
      mass_critic_rating_update: [mdb_metacritic, 2.0]
      mass_user_rating_update: [imdb, 2.0]
      delete_collections:
        configured: false
        managed: true
    minimum_items: 2
    radarr:
      url: http://4kradarr.media.svc.cluster.local:7878
      token: <<RADARR_UHD_API_KEY>>
      add_missing: false
      add_existing: false
      root_folder_path: "/media/baby_plex/movies-4k"
      monitor: true
      availability: announced
      quality_profile: UHD Bluray + WEB
      tag:
      search: false
      radarr_path:
      plex_path:
      upgrade_existing: false
  Movies:
    library_name: Movies
    run_order:
      - collections
      - metadata
      - operations
      - overlays
    collection_files:
      - repo: Movies.yaml
      - repo: People.yaml
      - pmm: basic
      - pmm: imdb
    overlay_files:
      - remove_overlays: false
      - repo: Movies - Overlays - Charts.yaml
      - repo: Movies - Overlays - Oscars.yaml
      - repo: Movies - Overlays - Ratings.yaml
      - repo: Movies - Overlays - Stand-up.yaml
      - repo: Movies - Overlays - Streaming Services.yaml
      - repo: Movies - Overlays - Studios.yaml
    operations:
      mass_genre_update: imdb
      mass_content_rating_update: [omdb, 2.0]
      mass_audience_rating_update: [mdb_tomatoesaudience, 2.0]
      mass_critic_rating_update: [mdb_metacritic, 2.0]
      mass_user_rating_update: [imdb, 2.0]
      delete_collections:
        configured: false
        managed: true
    minimum_items: 2
    radarr:
      url: http://radarr.media.svc.cluster.local:7878
      token: <<RADARR_API_KEY>>
      add_missing: false
      add_existing: false
      root_folder_path: "/media/baby_plex/Movies"
      monitor: true
      availability: announced
      quality_profile: HD Bluray + WEB
      tag:
      search: false
      radarr_path:
      plex_path:
      upgrade_existing: false
  4k-TV Shows:
    library_name: 4k-TV Shows
    run_order:
      - collections
      - metadata
      - operations
      - overlays
    collection_files:
      - repo: TV Shows.yaml
      - repo: People.yaml
      - default: cannes
      - default: basic
      - default: imdb
    overlay_files:
      - remove_overlays: false
      - repo: TV Shows - Overlays - Charts.yaml
      - repo: TV Shows - Overlays - Networks.yaml
      - repo: TV Shows - Overlays - Ratings.yaml
      - repo: TV Shows - Overlays - Statuses.yaml
      - repo: TV Shows - Overlays - Streaming Services.yaml
      - repo: TV Shows - Overlays - Studios.yaml
    minimum_items: 2
    operations:
      mass_genre_update: tmdb
      mass_content_rating_update: omdb
      mass_audience_rating_update: [mdb_tomatoesaudience, 2.0]
      mass_critic_rating_update: [mdb_metacritic, 2.0]
      mass_user_rating_update: [imdb, 2.0]
      mass_episode_audience_rating_update: [mdb_tomatoesaudience, 2.0]
      mass_episode_critic_rating_update: [mdb_metacritic, 2.0]
      mass_episode_user_rating_update: [imdb, 2.0]
      delete_collections:
        configured: false
        managed: true
    sonarr:
      url: http://4ksonarr.media.svc.cluster.local:80
      token: <<SONARR_UHD_API_KEY>>
      add_missing: false
      add_existing: false
      root_folder_path: "/media/baby_plex/tv-4k"
      monitor: all
      quality_profile: WEB-2160p
      language_profile: English
      series_type: standard
      season_folder: true
      tag:
      search: false
      cutoff_search: false
      sonarr_path:
      plex_path:
      upgrade_existing: false
  TV Shows:
    library_name: TV Shows
    run_order:
      - collections
      - metadata
      - operations
      - overlays
    collection_files:
      - repo: TV Shows.yaml
      - repo: People.yaml
      - default: cannes
      - default: basic
      - default: imdb
    overlay_files:
      - remove_overlays: false
      - repo: TV Shows - Overlays - Charts.yaml
      - repo: TV Shows - Overlays - Networks.yaml
      - repo: TV Shows - Overlays - Ratings.yaml
      - repo: TV Shows - Overlays - Statuses.yaml
      - repo: TV Shows - Overlays - Streaming Services.yaml
      - repo: TV Shows - Overlays - Studios.yaml
    minimum_items: 2
    operations:
      mass_genre_update: tmdb
      mass_content_rating_update: omdb
      mass_audience_rating_update: [mdb_tomatoesaudience, 2.0]
      mass_critic_rating_update: [mdb_metacritic, 2.0]
      mass_user_rating_update: [imdb, 2.0]
      mass_episode_audience_rating_update: [mdb_tomatoesaudience, 2.0]
      mass_episode_critic_rating_update: [mdb_metacritic, 2.0]
      mass_episode_user_rating_update: [imdb, 2.0]
      delete_collections:
        configured: false
        managed: true
    sonarr:
      url: http://sonarr.media.svc.cluster.local:80
      token: <<SONARR_API_KEY>>
      add_missing: false
      add_existing: false
      root_folder_path: "/media/baby_plex/Shows"
      monitor: all
      quality_profile: WEB-1080p
      language_profile: English
      series_type: standard
      season_folder: true
      tag:
      search: false
      cutoff_search: false
      sonarr_path:
      plex_path:
      upgrade_existing: false

settings:
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: false
  asset_depth: 0
  create_asset_folders: false
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: true
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: sync
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  missing_path: config/missing
  custom_repo: https://github.com/DapperDivers/dapper-cluster/tree/main/kubernetes/apps/media/kometa/app/custom
  only_filter_missing: false
  show_unmanaged: false
  show_filtered: false
  show_options: false
  show_missing: false
  show_missing_assets: false
  save_report: false
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_user: all
  playlist_exclude_user:
  playlist_report: false
  verify_ssl: true
  check_nightly: false
  show_unconfigured: true
  playlist_exclude_users:

plex:
  url: http://plex.media.svc.cluster.local:32400
  token: <<PLEX_TOKEN>>
  timeout: 60
  db_cache: 4096
  clean_bundles: true
  empty_trash: true
  optimize: false

tmdb: # REQUIRED for the script to run
  apikey: <<TMDB_API_KEY>>
  language: en
  cache_expiration: 60
  region:

tautulli:
  url: http://tautulli.media.svc.cluster.local:8181
  apikey: <<TAUTULLI_API_KEY>>

omdb:
  apikey: <<OMDB_API_KEY>>
  cache_expiration: 60

mdblist:
  apikey: <<MDBLIST_API_KEY>>
  cache_expiration: 60

# notifiarr:
#   API_KEY: <<NOTIFIARR_API_KEY>>
