---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../flux/components/common
resources:
  - ./media-nfs-storage/ks.yaml  # NFS PVCs - deprecated, using CephFS only
  - ./storage/ks.yaml  # CephFS static PVs
  #- ./autobrr/ks.yaml
  - ./bazarr/ks.yaml
  - ./bazarr-uhd/ks.yaml
  - ./tautulli/ks.yaml
  - ./recyclarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./sonarr-uhd/ks.yaml
  # - ./huntarr/ks.yaml
  - ./radarr/ks.yaml
  - ./radarr-uhd/ks.yaml
  - ./kometa/ks.yaml
  - ./posterizarr/ks.yaml
  # - ./nzbget/ks.yaml
  - ./tdarr/ks.yaml
  - ./threadfin/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./overseerr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./plex/ks.yaml
  - ./wizarr/ks.yaml
  - ./migrate-nfs/ks.yaml  # NFS migration - no longer needed
