---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: munin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: munin-secret
    template:
      engineVersion: v2
      data:
        # Gateway token for authentication
        CLAWDBOT_GATEWAY_TOKEN: "{{ .MUNIN_GATEWAY_TOKEN }}"
  dataFrom:
    - find:
        name:
          regexp: ^MUNIN.*
