---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: roundtable
components:
  - ../../flux/components/common
resources:
  - ./rbac/ks.yaml
  - ./galahad/ks.yaml
  - ./percival/ks.yaml
  - ./lancelot/ks.yaml
  - ./tristan/ks.yaml
  - ./bedivere/ks.yaml
  - ./kay/ks.yaml
