---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: percival
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: percival-secret
    template:
      engineVersion: v2
      data:
        ANTHROPIC_API_KEY: "{{ .OPENCLAW_ANTHROPIC_API_KEY }}"
        PAPERLESS_TOKEN: "{{ .PAPERLESS_TOKEN }}"
  dataFrom:
    - find:
        name:
          regexp: ^OPENCLAW.*
    - find:
        name:
          regexp: ^PAPERLESS_TOKEN$
