---
# Generated LiteLLM secrets - will be pushed to Infisical
apiVersion: v1
kind: Secret
metadata:
  name: litellm-generated
  labels:
    app.kubernetes.io/name: litellm
type: Opaque
stringData:
  LITELLM_MASTER_KEY: "sk-TrU80A6bn4ixweThS5wbl8QnKvjJ1yET"
  LITELLM_POSTGRES_USER: "litellm"
  LITELLM_POSTGRES_PASSWORD: "HucPxBZYr1QGx3pCaSHesWYA"
