---
# Push LiteLLM secrets to Infisical
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalPushSecret
metadata:
  name: litellm-secrets
spec:
  resyncInterval: 60m
  hostAPI: https://app.infisical.com/api

  updatePolicy: Replace
  deletionPolicy: None

  destination:
    projectId: 19edb415-e2e8-4dac-8583-5c470e66d0d1
    environmentSlug: prod
    secretsPath: /

  push:
    secret:
      secretName: litellm-generated
      secretNamespace: ai

  authentication:
    universalAuth:
      credentialsRef:
        secretName: infiscal-auth-secret
        secretNamespace: external-secrets
