---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: helm-opencti
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/dapperdivers/helm-opencti
  ref:
    branch: main
