---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tristan
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: tristan-secret
    template:
      engineVersion: v2
      data:
        ANTHROPIC_API_KEY: "{{ .OPENCLAW_ANTHROPIC_API_KEY }}"
  dataFrom:
    - find:
        name:
          regexp: ^OPENCLAW.*
