---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outlook-bridge
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: outlook-bridge-secret
    template:
      engineVersion: v2
      data:
        AZURE_CLIENT_ID: "{{ .OUTLOOK_BRIDGE_CLIENT_ID }}"
        AZURE_CLIENT_SECRET: "{{ .OUTLOOK_BRIDGE_CLIENT_SECRET }}"
        INTERNAL_TOKEN: "{{ .OUTLOOK_BRIDGE_INTERNAL_TOKEN }}"
  dataFrom:
    - find:
        name:
          regexp: ^OUTLOOK_BRIDGE.*
