---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kestra
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-postgres
  target:
    name: kestra-secret
    template:
      engineVersion: v2
      data:
        DATASOURCES_POSTGRES_URL: "jdbc:postgresql://{{ .POSTGRES_SUPER_HOST_RW }}.database.svc.cluster.local:5432/kestra"
        DATASOURCES_POSTGRES_USERNAME: "{{ .KESTRA_POSTGRES_USER }}"
        DATASOURCES_POSTGRES_PASSWORD: "{{ .KESTRA_POSTGRES_PASSWORD }}"
  dataFrom:
    - find:
        name:
          regexp: ^KESTRA.*
    - find:
        path: POSTGRES_SUPER_HOST_RW
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kestra-postgres
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-postgres
  target:
    name: kestra-postgres-secret
    template:
      engineVersion: v2
      data:
        INIT_POSTGRES_HOST: "{{ .POSTGRES_SUPER_HOST_RW }}.database.svc.cluster.local"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_DBNAME: kestra
        INIT_POSTGRES_USER: "{{ .KESTRA_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .KESTRA_POSTGRES_PASSWORD }}"
  dataFrom:
    - find:
        name:
          regexp: ^KESTRA.*
    - find:
        path: POSTGRES_SUPER_USER
    - find:
        path: POSTGRES_SUPER_PASS
    - find:
        path: POSTGRES_SUPER_HOST_RW
