---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kestra
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: kestra-secret
    template:
      engineVersion: v2
      data:
        MINIO_ACCESS_KEY: "{{ .KESTRA_MINIO_ACCESS_KEY }}"
        MINIO_SECRET_KEY: "{{ .KESTRA_MINIO_SECRET_KEY }}"
        CLAUDE_CODE_OAUTH_TOKEN: "{{ .KESTRA_CLAUDE_CODE_OAUTH_TOKEN }}"
  dataFrom:
    - find:
        name:
          regexp: ^KESTRA.*

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kestra-postgres
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-postgres
  target:
    name: kestra-postgres-secret
    template:
      engineVersion: v2
      data:
        INIT_POSTGRES_HOST: "{{ .POSTGRES_SUPER_HOST_RW }}.database.svc.cluster.local"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_DBNAME: kestra
        INIT_POSTGRES_USER: "{{ .KESTRA_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .KESTRA_POSTGRES_PASSWORD }}"
  dataFrom:
    - find:
        name:
          regexp: ^KESTRA.*
    - find:
        path: POSTGRES_SUPER_USER
    - find:
        path: POSTGRES_SUPER_PASS
    - find:
        path: POSTGRES_SUPER_HOST_RW
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kestra-datasources
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-postgres
  target:
    name: kestra-datasources-secret
    template:
      engineVersion: v2
      data:
        DATASOURCES_POSTGRES_USERNAME: "{{ .KESTRA_POSTGRES_USER }}"
        DATASOURCES_POSTGRES_PASSWORD: "{{ .KESTRA_POSTGRES_PASSWORD }}"
  dataFrom:
    - find:
        path: KESTRA_POSTGRES_USER
    - find:
        path: KESTRA_POSTGRES_PASSWORD
