---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kestra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kestra-task-runner
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["create", "get", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kestra-task-runner
subjects:
  - kind: ServiceAccount
    name: kestra
roleRef:
  kind: Role
  name: kestra-task-runner
  apiGroup: rbac.authorization.k8s.io
