---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bedivere
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: bedivere-secret
    template:
      engineVersion: v2
      data:
        ANTHROPIC_API_KEY: "{{ .OPENCLAW_ANTHROPIC_API_KEY }}"
        HOMEASSISTANT_TOKEN: "{{ .MOLT_HOMEASSISTANT_TOKEN }}"
  dataFrom:
    - find:
        name:
          regexp: ^OPENCLAW.*
    - find:
        name:
          regexp: ^MOLT_HOMEASSISTANT_TOKEN$
