---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: galahad
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: galahad-secret
    template:
      engineVersion: v2
      data:
        OPENCLAW_GATEWAY_TOKEN: "{{ .OPENCLAW_GATEWAY_TOKEN }}"
        CLAWDBOT_GATEWAY_TOKEN: "{{ .OPENCLAW_GATEWAY_TOKEN }}"
        ANTHROPIC_API_KEY: "{{ .OPENCLAW_ANTHROPIC_API_KEY }}"
  dataFrom:
    - find:
        name:
          regexp: ^OPENCLAW.*
