---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: voice-ingest
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: voice-ingest-secret
    template:
      engineVersion: v2
      data:
        OPENCLAW_HOOK_TOKEN: "{{ .VOICE_INGEST_HOOK_TOKEN }}"
  dataFrom:
    - find:
        name:
          regexp: ^VOICE_INGEST.*
